### ISSUE TITLE
UNCLASSIFIED_ERROR when I run TestNG test and send the reports to RP

### ISSUE THREAD

**Issue by prvns133t** [reportportal/agent-java-testNG#30]
I installed RP and also configured it based on the instructions in the documentation. I was able to signin successfully into the portal. Also I got the UDID and updated the `reportportal.proprties`. 

However I see the following error when I run the test case provided in the github example testng project.

```
[RemoteTestNG] detected TestNG version 6.13.1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-10-10 10:06:54,490 [main] INFO  com.epam.rp.tests.logging.JsonLoggingTest - RP_MESSAGE#BASE64#ewogICJURlMiOiB7CiAgICAiYnVpbGQiOiB7CiAgICAgICJuYW1lIjogIlRGUyBTZXJ2aWNlIiwKICAgICAgImRlc2NyaXB0aW9uIjogIlJlcG9ydFBvcnRhbCBURlMgSW50ZWdyYXRpb24iLAogICAgICAidmVyc2lvbiI6ICIyLjUuMS4zLVNOQVBTSE9UIiwKICAgICAgImJyYW5jaCI6ICJIRUFELWY2NDllMWNjZWM2NmI3YzdmZDdhNzc4NzY4NjI3YzI4ZThjY2JkMmUiCiAgICB9CiAgfSwKICAiR0FURVdBWSI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiR2F0ZXdheSBTZXJ2aWNlIiwKICAgICAgImRlc2NyaXB0aW9uIjogIlJlcG9ydFBvcnRhbCBHYXRld2F5IFNlcnZpY2UiLAogICAgICAidmVyc2lvbiI6ICIzLjAuMC1TTkFQU0hPVCIsCiAgICAgICJicmFuY2giOiAiSEVBRC03MDUyNTBmNGI0NmIzMjZmY2E2NjY4MWE2ZGU3MzZhMzg4OTQyNmE2IgogICAgfQogIH0sCiAgIlVJIjogewogICAgImJ1aWxkIjogewogICAgICAibmFtZSI6ICJVSSBTZXJ2aWNlIiwKICAgICAgImRlc2NyaXB0aW9uIjogIlJlcG9ydFBvcnRhbCBVc2VyIEludGVyZmFjZSIsCiAgICAgICJ2ZXJzaW9uIjogIjIuNy4xLVNOQVBTSE9UIiwKICAgICAgImJyYW5jaCI6ICJAYnJhbmNoQCIKICAgIH0KICB9LAogICJSQUxMWSI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiUmFsbHkgU2VydmljZSIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXBvcnRQb3J0YWwgUmFsbHkgSW50ZWdyYXRpb24iLAogICAgICAidmVyc2lvbiI6ICIyLjcuMS1TTkFQU0hPVCIsCiAgICAgICJicmFuY2giOiAiSEVBRC01Y2VkOTg5NDM0MWM0MTg4YjQ2NzkzOGNlYjE2M2E2YzUyNDRmNTU4IgogICAgfQogIH0sCiAgIlVBVCI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiQXV0aG9yaXphdGlvbiBTZXJ2aWNlIiwKICAgICAgImRlc2NyaXB0aW9uIjogIlVuaWZpZWQgQXV0aG9yaXphdGlvbiBUcmFwIGZvciBhbGwgUmVwb3J0UG9ydGFsJ3MgU2VydmljZXMiLAogICAgICAidmVyc2lvbiI6ICIyLjcuMi1TTkFQU0hPVCIsCiAgICAgICJicmFuY2giOiAiSEVBRC1iM2RiMThkOGNhNDJiYTRkYzJjYmUyYTg2ZDM0ODA4Mzg2OTMxZmM3IgogICAgfSwKICAgICJhdXRoX2V4dGVuc2lvbnMiOiBbCiAgICAgICJnaXRodWIiCiAgICBdCiAgfSwKICAiQVBJIjogewogICAgImJ1aWxkIjogewogICAgICAibmFtZSI6ICJBUEkgU2VydmljZSIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXBvcnRQb3J0YWwgQVBJIFNlcnZpY2UiLAogICAgICAidmVyc2lvbiI6ICIzLjAuMC1TTkFQU0hPVCIsCiAgICAgICJicmFuY2giOiAiSEVBRC01MmRlZGMwNjU1NDlhOTg5NTFkOTUzMGVjOGE4MGIwZTUxYTcyZmU5IgogICAgfQogIH0sCiAgIkpJUkEiOiB7CiAgICAiYnVpbGQiOiB7CiAgICAgICJuYW1lIjogIkppcmEgU2VydmljZSIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXBvcnRQb3J0YWwgSmlyYSBJbnRlZ3JhdGlvbiIsCiAgICAgICJ2ZXJzaW9uIjogIjIuNy4xLVNOQVBTSE9UIiwKICAgICAgImJyYW5jaCI6ICJIRUFELTNkNGRhMDcyZDE1MDQ5ZWYwMTM3NjgxZTVkYTgzZmNiMGYyNDBjNmUiCiAgICB9CiAgfSwKICAiUkVHSVNUUlkiOiB7CiAgICAiYnVpbGQiOiB7CiAgICAgICJuYW1lIjogIlJlZ2lzdHJ5IFNlcnZpY2UiLAogICAgICAiZGVzY3JpcHRpb24iOiAiUmVwb3J0UG9ydGFsIFJlZ2lzdHJ5IGFuZCBDb25maWd1cmF0aW9uIFNlcnZpY2UiLAogICAgICAidmVyc2lvbiI6ICIyLjcuMi1TTkFQU0hPVCIsCiAgICAgICJicmFuY2giOiAiSEVBRC1hNWJmMjk2NDgzOTI4ZWMyNzllYWI2NzA1M2M5NzFlZGQ2MDEwZmU4IgogICAgfQogIH0KfQo=#I'm logging content via BASE64
2018-10-10 10:06:54,519 [main] INFO  com.epam.rp.tests.logging.JsonLoggingTest - RP_MESSAGE#FILE#/var/folders/x6/lt7jmf5x43scwmbrk_t8mdbr0000gn/T/rp-test7492796823510463939.json#I'm logging content via temp file
io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:50)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:486)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:455)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 13 more

```

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu @pbortnik @akoltochihin 
Guys, any ideas on 500 error?

**Comment by filland** [comment]
@prvns133t did you manage to solve the problem ?

**Comment by prvns133t** [comment]
Yes I did. I think I just upgraded or downgraded(Don't remember exactly)
some of the components manually and it worked.

**Comment by DzmitryHumianiuk** [comment]
@prvns133t so looks like it is resolved.
closing.

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk I still get this error. Do you know how this ticket was resolved?
I'm running https://github.com/reportportal/example-java-TestNG with logback. 

I have setup the report-portal project appropriately. Using latest version (4.3.6)

![image](https://user-images.githubusercontent.com/47788194/55018239-4e882e80-4fea-11e9-9963-82ff8a639e91.png)

Console o/p
```
[RemoteTestNG] detected TestNG version 6.14.3
17:00:34.417 WARN  c.e.r.t.BaseTestNGListener - main - WARNING! More than one ReportPortal listener is added
WARNING! More than one ReportPortal listener is added
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
17:00:35.301 INFO  c.e.r.s.Launch - main - Not rerun!
17:00:35.918 DEBUG c.e.r.s.Launch - rp-io-0 - ReportPortal launch with ID '5c9a5ac61f4b95000153f12b' has been created
17:00:35.921 DEBUG c.e.r.u.LaunchFile - rp-io-0 - ReportPortal's temp file 'C:\Users\XXXX~1\AppData\Local\Temp\2\reportportal\rplaunch-SampleProjectTest-#2-5c9a5ac61f4b95000153f12b.tmp' is created
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch file create successfully completed
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch start successfully completed
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch start successfully completed
17:00:35.987 DEBUG c.e.r.s.Launch - rp-io-1 - ReportPortal item with ID '5c9a5ac61f4b95000153f12d' has been created
17:00:35.987 DEBUG c.e.r.u.SubscriptionUtils - rp-io-1 - Start test item successfully completed
17:00:35.987 DEBUG c.e.r.s.Launch - rp-io-1 - Starting test item...rp-io-1
17:00:36.029 DEBUG c.e.r.s.Launch - rp-io-2 - ReportPortal item with ID '5c9a5ac61f4b95000153f12e' has been created
17:00:36.029 DEBUG c.e.r.u.SubscriptionUtils - rp-io-2 - Start test item successfully completed
17:00:36.029 DEBUG c.e.r.s.Launch - rp-io-2 - Starting test item...rp-io-2
17:00:36.048 DEBUG c.e.r.s.Launch - rp-io-3 - ReportPortal item with ID '5c9a5ac61f4b95000153f12f' has been created
17:00:36.048 DEBUG c.e.r.u.SubscriptionUtils - rp-io-3 - Start test item successfully completed
17:01:15.365 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 0
17:01:20.431 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 1
17:01:27.845 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 2
17:01:30.587 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 3
17:01:32.205 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 4
17:01:33.821 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 5
17:01:35.439 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 6
17:01:36.853 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 7
17:01:38.066 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 8
17:01:39.276 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 9
17:02:11.685 ERROR c.e.r.s.Launch - rp-io-5 - [25] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
17:02:11.685 ERROR c.e.r.u.SubscriptionUtils - rp-io-5 - [25] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
17:02:45.032 DEBUG c.e.r.s.Launch - TestNG-PoolService-0 - Starting test item...TestNG-PoolService-0
17:02:45.032 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:45.033 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:45.039 DEBUG c.e.r.s.Launch - TestNG-PoolService-1 - Starting test item...TestNG-PoolService-1
17:02:45.039 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:45.040 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:45.042 DEBUG c.e.r.s.Launch - TestNG-PoolService-2 - Starting test item...TestNG-PoolService-2
17:02:45.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:45.043 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:45.058 DEBUG c.e.r.s.Launch - rp-io-6 - ReportPortal item with ID '5c9a5b471f4b95000153f13a' has been created
17:02:45.058 DEBUG c.e.r.u.SubscriptionUtils - rp-io-6 - Start test item successfully completed
17:02:45.060 DEBUG c.e.r.s.Launch - rp-io-7 - ReportPortal item with ID '5c9a5b471f4b95000153f13b' has been created
17:02:45.060 DEBUG c.e.r.u.SubscriptionUtils - rp-io-7 - Start test item successfully completed
17:02:45.066 DEBUG c.e.r.s.Launch - rp-io-8 - ReportPortal item with ID '5c9a5b471f4b95000153f13c' has been created
17:02:45.067 DEBUG c.e.r.u.SubscriptionUtils - rp-io-8 - Start test item successfully completed
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.041 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.041 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.046 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.046 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.053 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.053 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
```

**Comment by DzmitryHumianiuk** [comment]
logs from @arunkumar-muthusamy
```logs
[RemoteTestNG] detected TestNG version 6.14.3
17:00:34.417 WARN  c.e.r.t.BaseTestNGListener - main - WARNING! More than one ReportPortal listener is added
WARNING! More than one ReportPortal listener is added
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
[TestNG] [WARN] Ignoring duplicate listener : com.epam.reportportal.testng.ReportPortalTestNGListener
17:00:35.301 INFO  c.e.r.s.Launch - main - Not rerun!
17:00:35.918 DEBUG c.e.r.s.Launch - rp-io-0 - ReportPortal launch with ID '5c9a5ac61f4b95000153f12b' has been created
17:00:35.921 DEBUG c.e.r.u.LaunchFile - rp-io-0 - ReportPortal's temp file 'C:\Users\XXXX~1\AppData\Local\Temp\2\reportportal\rplaunch-SampleProjectTest-#2-5c9a5ac61f4b95000153f12b.tmp' is created
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch file create successfully completed
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch start successfully completed
17:00:35.922 DEBUG c.e.r.u.SubscriptionUtils - rp-io-0 - Launch start successfully completed
17:00:35.987 DEBUG c.e.r.s.Launch - rp-io-1 - ReportPortal item with ID '5c9a5ac61f4b95000153f12d' has been created
17:00:35.987 DEBUG c.e.r.u.SubscriptionUtils - rp-io-1 - Start test item successfully completed
17:00:35.987 DEBUG c.e.r.s.Launch - rp-io-1 - Starting test item...rp-io-1
17:00:36.029 DEBUG c.e.r.s.Launch - rp-io-2 - ReportPortal item with ID '5c9a5ac61f4b95000153f12e' has been created
17:00:36.029 DEBUG c.e.r.u.SubscriptionUtils - rp-io-2 - Start test item successfully completed
17:00:36.029 DEBUG c.e.r.s.Launch - rp-io-2 - Starting test item...rp-io-2
17:00:36.048 DEBUG c.e.r.s.Launch - rp-io-3 - ReportPortal item with ID '5c9a5ac61f4b95000153f12f' has been created
17:00:36.048 DEBUG c.e.r.u.SubscriptionUtils - rp-io-3 - Start test item successfully completed
17:01:15.365 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 0
17:01:20.431 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 1
17:01:27.845 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 2
17:01:30.587 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 3
17:01:32.205 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 4
17:01:33.821 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 5
17:01:35.439 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 6
17:01:36.853 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 7
17:01:38.066 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 8
17:01:39.276 INFO  c.e.r.t.e.ParameterizedTest - TestNG-test=Parametrized Test-1 - My great message: 9
17:02:11.685 ERROR c.e.r.s.Launch - rp-io-5 - [25] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
17:02:11.685 ERROR c.e.r.u.SubscriptionUtils - rp-io-5 - [25] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 500
Status message: Internal Server Error
Error Message: Unclassified error [null]
Error Type: UNCLASSIFIED_ERROR

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
17:02:45.032 DEBUG c.e.r.s.Launch - TestNG-PoolService-0 - Starting test item...TestNG-PoolService-0
17:02:45.032 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:45.033 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:45.039 DEBUG c.e.r.s.Launch - TestNG-PoolService-1 - Starting test item...TestNG-PoolService-1
17:02:45.039 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:45.040 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:45.042 DEBUG c.e.r.s.Launch - TestNG-PoolService-2 - Starting test item...TestNG-PoolService-2
17:02:45.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:45.043 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:45.058 DEBUG c.e.r.s.Launch - rp-io-6 - ReportPortal item with ID '5c9a5b471f4b95000153f13a' has been created
17:02:45.058 DEBUG c.e.r.u.SubscriptionUtils - rp-io-6 - Start test item successfully completed
17:02:45.060 DEBUG c.e.r.s.Launch - rp-io-7 - ReportPortal item with ID '5c9a5b471f4b95000153f13b' has been created
17:02:45.060 DEBUG c.e.r.u.SubscriptionUtils - rp-io-7 - Start test item successfully completed
17:02:45.066 DEBUG c.e.r.s.Launch - rp-io-8 - ReportPortal item with ID '5c9a5b471f4b95000153f13c' has been created
17:02:45.067 DEBUG c.e.r.u.SubscriptionUtils - rp-io-8 - Start test item successfully completed
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.034 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-0 - one: two
17:02:50.041 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.041 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.042 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.046 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-1 - two: one
17:02:50.046 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.052 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.053 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null
17:02:50.053 INFO  c.e.r.t.e.ParameterizedTest - TestNG-PoolService-2 - three: null

```

**Comment by DzmitryHumianiuk** [comment]
asked for help if slack chat

**Comment by arunkumar-muthusamy** [comment]
@DzmitryHumianiuk , its my bad.. i did configure the project name incorrectly. i thought i deleted the comment.. Please disregard it.. Working fine for me.

**Comment by avarabyeu** [comment]
That is s a good one. Can you attach the logs of service-api? The error comes from there

**Comment by arunkumar-muthusamy** [comment]
@avarabyeu, please ignore my comment. i did configure the rpo project name incorrectly in the properties file, which caused these 500 error.
